#!/bin/sh
echo Starting Webmin server in /usr/libexec/webmin
trap '' 1
LANG=
export LANG
#PERLIO=:raw
unset PERLIO
export PERLIO
PERLLIB=/usr/libexec/webmin
export PERLLIB
exec '/usr/libexec/webmin/miniserv.pl' //etc/webmin/miniserv.conf
